Add check and better error message for file existence

diff --git a/templatectl b/templatectl
--- a/templatectl
+++ b/templatectl
@@ -66,16 +66,26 @@ list_check_environment_scripts() {
 	echo "${scripts[@]}"
 }
 
+verify_check_environment_script() {
+	local SCRIPT=$1
+
+	if ! [[ -e $SCRIPT ]]; then
+		err "'$SCRIPT' cannot be found. Aborting."
+		return 1
+	fi
+
+	if ! [[ -x $SCRIPT ]]; then
+		err "'$SCRIPT' is not executable. Aborting."
+		return 1
+	fi
+}
+
 check_environment() {
-	local NAME=$1-check-environment
-	local SCRIPT=$2
+	local SCRIPT=$1
 	local CUSTOM=''
-	local CHECK=${SCRIPT%%/files/check-environment}
-	CHECK=${CHECK##*[./]}
 	[[ $CUSTOM_CHECK_ENVIRONMENT ]] && CUSTOM='custom-'
 
-	$SUDO cp $SCRIPT $BINDIR/${NAME}
-	if ! OUT=$(docker_run $IMAGE bash -lc ${NAME} 2>&1); then
+	verify_check_environment_script "$SCRIPT"
 	$SUDO cp $SCRIPT $BINDIR/${TEMPLATE}-${custom}check-environment
 	if ! OUT=$(docker_run $IMAGE bash -lc ${TEMPLATE}-${custom}check-environment 2>&1); then
 		err "$OUT"
